// Mock data that simulates what would be stored in MongoDB

// Teams Collection
export const teams = [
  {
    _id: "team1",
    name: "Mountain Goats",
    score: 1245,
    maxScore: 1500,
    captain: "user1", // Reference to user ID
    winRate: 80,
    members: ["user1", "user4", "user6", "user8", "user10", "user12", "user14", "user16"],
    createdAt: new Date("2025-01-15").toISOString(),
    competitionId: "comp2025",
  },
  {
    _id: "team2",
    name: "Royal Rams",
    score: 1198,
    maxScore: 1500,
    captain: "user2",
    winRate: 75,
    members: ["user2", "user5", "user7", "user9", "user11", "user13", "user15", "user17"],
    createdAt: new Date("2025-01-15").toISOString(),
    competitionId: "comp2025",
  },
  {
    _id: "team3",
    name: "Athletic Antelopes",
    score: 1056,
    maxScore: 1500,
    captain: "user3",
    winRate: 70,
    members: ["user3", "user18", "user19", "user20", "user21", "user22", "user23"],
    createdAt: new Date("2025-01-16").toISOString(),
    competitionId: "comp2025",
  },
  {
    _id: "team4",
    name: "Speed Sheep",
    score: 987,
    maxScore: 1500,
    captain: "user24",
    winRate: 65,
    members: ["user24", "user25", "user26", "user27", "user28", "user29"],
    createdAt: new Date("2025-01-16").toISOString(),
    competitionId: "comp2025",
  },
]

// Users Collection
export const users = [
  {
    _id: "user1",
    name: "Sarah Johnson",
    email: "sarah.johnson@example.com",
    role: "captain",
    teamId: "team1",
    proficiencyScore: 98,
    titles: ["GOAT '24"],
    position: "Captain",
    proficiencies: [
      { name: "Basketball", score: 95 },
      { name: "Soccer", score: 90 },
      { name: "Volleyball", score: 85 },
      { name: "Swimming", score: 80 },
      { name: "Running", score: 95 },
      { name: "Strategy Games", score: 85 },
    ],
    createdAt: new Date("2022-01-10").toISOString(),
  },
  {
    _id: "user2",
    name: "Michael Chen",
    email: "michael.chen@example.com",
    role: "captain",
    teamId: "team2",
    proficiencyScore: 96,
    titles: ["MVP '24"],
    position: "Captain",
    proficiencies: [
      { name: "Basketball", score: 92 },
      { name: "Soccer", score: 88 },
      { name: "Swimming", score: 95 },
      { name: "Strategy Games", score: 90 },
    ],
    createdAt: new Date("2022-01-12").toISOString(),
  },
  {
    _id: "user3",
    name: "James Wilson",
    email: "james.wilson@example.com",
    role: "captain",
    teamId: "team3",
    proficiencyScore: 95,
    titles: [],
    position: "Captain",
    proficiencies: [
      { name: "Basketball", score: 90 },
      { name: "Soccer", score: 92 },
      { name: "Running", score: 94 },
    ],
    createdAt: new Date("2022-02-05").toISOString(),
  },
  {
    _id: "user4",
    name: "Emily Rodriguez",
    email: "emily.rodriguez@example.com",
    role: "player",
    teamId: "team1",
    proficiencyScore: 94,
    titles: ["Rookie '24"],
    position: "Member",
    proficiencies: [
      { name: "Volleyball", score: 96 },
      { name: "Swimming", score: 92 },
    ],
    createdAt: new Date("2023-01-15").toISOString(),
  },
  {
    _id: "user5",
    name: "David Kim",
    email: "david.kim@example.com",
    role: "player",
    teamId: "team2",
    proficiencyScore: 93,
    titles: [],
    position: "Member",
    proficiencies: [
      { name: "Basketball", score: 94 },
      { name: "Strategy Games", score: 92 },
    ],
    createdAt: new Date("2023-02-10").toISOString(),
  },
  // Add more users as needed
]

// Competitions Collection
export const competitions = [
  {
    _id: "comp2025",
    name: "Eid-Al-Athletes",
    year: 2025,
    startDate: new Date("2025-06-15").toISOString(),
    endDate: new Date("2025-07-30").toISOString(),
    status: "active",
    description: "The ultimate athletic showdown to crown the GOAT",
    teams: ["team1", "team2", "team3", "team4"],
    games: ["game1", "game2", "game3", "game4", "game5", "game6"],
    createdAt: new Date("2025-01-01").toISOString(),
  },
  {
    _id: "comp2024",
    name: "Royal Rumble",
    year: 2024,
    startDate: new Date("2024-05-10").toISOString(),
    endDate: new Date("2024-06-25").toISOString(),
    status: "completed",
    description: "A regal competition to determine the true Malik",
    winner: "team1",
    goat: "user1",
    teams: ["team1", "team2", "team5", "team6"],
    games: ["game7", "game8", "game9", "game10", "game11", "game12"],
    createdAt: new Date("2024-01-01").toISOString(),
  },
]

// Games Collection
export const games = [
  {
    _id: "game1",
    name: "Basketball Tournament",
    type: "Team Sport",
    date: new Date("2025-06-15").toISOString(),
    team1: "team1",
    team2: "team2",
    score1: 78,
    score2: 72,
    status: "completed",
    location: "Main Arena",
    pointsValue: 100,
    competitionId: "comp2025",
  },
  {
    _id: "game2",
    name: "Soccer Match",
    type: "Team Sport",
    date: new Date("2025-06-18").toISOString(),
    team1: "team3",
    team2: "team1",
    score1: 2,
    score2: 3,
    status: "completed",
    location: "Main Field",
    pointsValue: 100,
    competitionId: "comp2025",
  },
  {
    _id: "game3",
    name: "Volleyball Tournament",
    type: "Team Sport",
    date: new Date("2025-06-22").toISOString(),
    team1: "team1",
    team2: "team4",
    status: "scheduled",
    location: "Main Arena",
    pointsValue: 100,
    competitionId: "comp2025",
  },
  {
    _id: "game4",
    name: "Relay Race",
    type: "Relay",
    date: new Date("2025-06-25").toISOString(),
    team1: "team2",
    team2: "team3",
    status: "scheduled",
    location: "Track Field",
    pointsValue: 200,
    competitionId: "comp2025",
  },
  {
    _id: "game5",
    name: "Swimming Competition",
    type: "Individual",
    date: new Date("2025-06-28").toISOString(),
    status: "scheduled",
    location: "Aquatic Center",
    pointsValue: 150,
    competitionId: "comp2025",
  },
  {
    _id: "game6",
    name: "Strategy Challenge",
    type: "Strategy",
    date: new Date("2025-07-02").toISOString(),
    status: "scheduled",
    location: "Conference Hall",
    pointsValue: 300,
    competitionId: "comp2025",
  },
]

